version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: polyclinic-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polyclinic
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: polyclinic-back
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "3000:3000"

volumes:
  pgdata:
