rebuild:
	docker compose down -v
	docker compose build --no-cache
	docker compose up -d

up:
	docker compose up -d

down:
	docker compose down

logs:
	docker compose logs -f backend

ps:
	docker compose ps
